version: "3"

services:
  web:
    container_name: coderang
    build:
      context: .
      dockerfile: ./apps/coderang/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    external: true
