version: 2.1

jobs:
  install_deps:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install -g pnpm@8.15.7
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "pnpm-lock.yaml" }}
            - deps-v1-{{ .Branch }}
      - run:
          name: Install dependencies
          command: pnpm install
      - save_cache:
          key: deps-v1-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
            - .pnpm-store

  build:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "pnpm-lock.yaml" }}
            - deps-v1-{{ .Branch }}
      - run:
          name: Build the project
          command: pnpm build

  test:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "pnpm-lock.yaml" }}
            - deps-v1-{{ .Branch }}
      - run:
          name: Run tests
          command: pnpm test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_deps
      - build:
          requires:
            - install_deps
      - test:
          requires:
            - install_deps
