export interface Post {
  __typename?: string;
  id: string;
  title?: string;
  titleHtml?: string;
  permalink?: string;
  image: string;
  content?: string;
  contentHtml?: string;
  createdAt?: string;
  pinnedAt?: Date | string;
  readTime?: number;
  tags?: string[];
  numCollectionSources?: number;
  upvoted?: boolean;
  commented?: boolean;
  commentsPermalink: string;
  numUpvotes?: number;
  numComments?: number;
  views?: number;
  placeholder?: string;
  read?: boolean;
  bookmarked?: boolean;
  trending?: number;
  description?: string;
  summary?: string;
  impressionStatus?: number;
  isAuthor?: number;
  isScout?: number;
  private?: boolean;
  feedMeta?: string;
  downvoted?: boolean;
  videoId?: string;
  updatedAt?: string;
  slug?: string;
}
